service: selenium-lambda

provider:
  name: aws
  runtime: python3.6
  region: us-east-1
  timeout: 900

functions:
  main:
    memorySize: 1000
    handler: handler.lambda_handler
    events:
      - http:
          path: test
          method: get

    layers:
      - arn:aws:lambda:us-east-1:428232153938:layer:chromedriver:1
      - arn:aws:lambda:us-east-1:428232153938:layer:selenium:1



